server.port: 8080

spring.profiles.active: "dev"
# spring.main.wepb-application-type: none

# log config
logging.level.root: INFO
logging.level.org.springframework: INFO
logging.level.org.keron.microservicevisualization: DEBUG

# datasource config
spring.datasource.url: jdbc:h2:file:./h2/app_db;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: sa
spring.datasource.password: sa

# JPA config
spring.jpa.hibernate.ddl-auto: none
spring.jpa.show-sql: true
spring.jpa.properties.hibernate.format_sql: true

# H2 config
spring.h2.console.enabled: true
# spring.h2.console.path: /h2-console

## app config
micro.vis.index : forward:app-index.html